# Generated by Django 5.1.5 on 2025-01-21 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_check_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lvl',
            field=models.IntegerField(default=1, verbose_name='Уровень игрока'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата регистрации игрока'),
            preserve_default=False,
        ),
    ]
