# Generated by Django 5.1.5 on 2025-02-04 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_check_core', '0003_alter_userprofile_user_id_matrixlevel_matrixposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matrixlevel',
            options={'verbose_name': 'Матрица пользователя', 'verbose_name_plural': 'Матрицы пользователя'},
        ),
        migrations.AlterModelOptions(
            name='matrixposition',
            options={'verbose_name': 'Матрица с рефералами', 'verbose_name_plural': 'Матрицы с рефералами'},
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='top_check_core.userprofile', verbose_name='Приглашённый пользователь '),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='top_check_core.userprofile', verbose_name='Пригласивший'),
        ),
    ]
