# Generated by Django 5.1.5 on 2025-02-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_check_core', '0004_alter_matrixlevel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='Баланс пользователя'),
        ),
    ]
