# Generated by Django 5.1.5 on 2025-02-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_check_core', '0005_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pay_comfort',
            field=models.BooleanField(default=False, verbose_name='Оплачен тариф комфорт'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pay_exclusive',
            field=models.BooleanField(default=False, verbose_name='Оплачен тариф эксклюзив'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pay_premium',
            field=models.BooleanField(default=False, verbose_name='Оплачен тариф премиум'),
        ),
    ]
